inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'test/**/*'

Style/Documentation:
  Enabled: false
