name: "gatareview-back CI"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.33
        ports:
          - "3306:3306"
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot --silent"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
          --health-start-period=30s
          
    env:
      RAILS_ENV: test
      JWT_SECRET_KEY: test-jwt-secret-key

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2' 
          bundler-cache: true

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Copy database configuration
        run: cp config/database.yml.ci config/database.yml

      - name: Set up database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run RSpec tests
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET_KEY: test-jwt-secret-key
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run RuboCop
        run: bundle exec rubocop
